[package]
name = "nostr-sdk-flutter"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
flutter_rust_bridge = "=2.0.0"
nostr-sdk = { workspace = true, default-features = false, features = [
    "all-nips",
] }

[build-dependencies]
flutter_rust_bridge_codegen = "=2.0.0"
